### ISSUE TITLE
Cloudflare CDNJS is outdated.

### ISSUE THREAD

**Issue by fisharebest** [morteza/bootstrap-rtl#55]
This package is available via the cloudflare CDN: http://cdnjs.com/libraries/bootstrap-rtl

But the latest package there is only 3.2.0-rc2

Can this be updated?

**Comment by morteza** [comment]
Sure, it's just cumbersome process. Read [cdnjs readme](https://github.com/cdnjs/cdnjs/blob/master/README.md) if you are interested submitting the latest version to cdnjs.

Otherwise you can use rawgit cdn (#50). In this case, the cdn url to the latest version is http://cdn.rawgit.com/morteza/bootstrap-rtl/master/dist/cdnjs/3.3.1-rc2/css/bootstrap-rtl.min.css
