### ISSUE TITLE
Bootstrap v3.3.4

### ISSUE THREAD

**Issue by afattahi54** [morteza/bootstrap-rtl#66]
Has anyone tested the bootstrap-rtl with bootstrap 3.3.2 ?!
I have upgraded, made a quick look and did not find any issues. 
Any idea ?!

**Comment by morteza** [comment]
There is not much to change, only one issue to match the new version, and it's changing the selector of last and first children of button groups (to set respective left or right border radius).

Here is list of changes, mostly unrelated to the right-to-left representation:

- New WOFF2 Glyphicon font.
- Some new icons.
- Striped table uses `nth-of-type` instead of `nth-child` for odd rows.
- Line heights of `input-group-sm` and `input-group-lg` for data, time, datatime-local, and month inputs.
- `input-lg` and `input-sm` improvements for selects and textareas.
- `form-control-static`.
- `drop-up`s (it's just just like dropdown, speaking of stylings).
- Bottom margin for dropdown and dropup menus.
- New selector for right border radius for last child of `btn-groups`.
- New selector for left border radius for first child of `btn-group`.
- Bottom margin for dropdowns menus of fixed bottom navbars.
- `media-body` and `media-object` display.
- Color of `small`s inside `panel-tilte`.
- Line height for next and prev carousel icons.

**Comment by evilaliv3** [comment]
Bootstrap 3.3.4 is out.
I suggest to skip the release of a 3.3.2 version and work directly on that.
if agreed, withou opening a new ticket name of this should be changed and so the milestone name.

**Comment by morteza** [comment]
I've run a diff on 3.3.4 vs 3.3.2, and fortunately it does not seem to have any impact on rtl rendering. Let me know if there is any bug.
.
This issue and the milestone are both changed to match latest version.

**Comment by evilaliv3** [comment]
hi morteza, is there any update on this release?

**Comment by morteza** [comment]
@evilali3 Nothing new. There is a `3.3.4-rc1` tag now, but it might need some minor updates. Rather than that, you can  just bump the version.

**Comment by evilaliv3** [comment]
to keep in mind before closing this ticket: https://github.com/morteza/bootstrap-rtl/issues/70
